[build]
  # Dossier à publier
  publish = "frontend"
  
  # Commande de build (pas nécessaire pour un site statique)
  command = "echo 'Site statique - pas de build nécessaire'"

[build.environment]
  # Variables d'environnement si nécessaire
  NODE_VERSION = "18"

# Configuration des redirections et headers
[[headers]]
  # Headers pour tous les fichiers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers spécifiques pour les assets statiques
[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirections si nécessaire (exemple)
# [[redirects]]
#   from = "/old-page"
#   to = "/new-page"
#   status = 301
