[build]
  publish = "frontend"
  command = "echo 'No build step required for static site'"

# Image optimization settings
[[plugins]]
  package = "@netlify/plugin-image-optim"

# Headers for better performance
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Image transformation settings
[build.environment]
  NETLIFY_IMAGE_CDN = "true"

# Redirects for better SEO
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"